widgets_from_file = [
{
    "guid": "1",
    "x_element_type": "widget",
    "title": "Activity Loader Widget",
    "spanClass":"",
    "cssClass":"purple-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"3",
        "title":"Lesson 1",
        "badge":"icon-comment",
        // "badge":"activity.png",
        "information_text":"Coming soon",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "2",
    "x_element_type": "widget",
    "title": "Activity Loader Widget",
    "spanClass":"",
    "cssClass":"purple-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"3",
        "title":"Lesson 2",
        "badge":"icon-comment-alt",
        // "badge":"activity.png",
        "information_text":"Coming soon",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "3",
    "x_element_type": "widget",
    "title": "Activity Loader Widget",
    "spanClass":"",
    "cssClass":"purple-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"3",
        "title":"Lesson 3",
        "badge":"icon-comments",
        // "badge":"activity.png",
        "information_text":"Coming soon",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature.",
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "4",
    "x_element_type": "widget",
    "title": "Activity Loader Widget",
    "spanClass":"",
    "cssClass":"purple-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"3",
        "title":"Lesson 4",
        "badge":"icon-comments-alt",
        // "badge":"activity.png",
        "information_text":"Coming soon",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature.",
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "5",
    "x_element_type": "widget",
    "title": "Activity Loader Widget",
    "spanClass":"",
    "cssClass":"purple-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"3",
        "title":"Lesson 5",
        "badge":"icon-comments",
        // "badge":"activity.png",
        "information_text":"Coming soon",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature.",
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "6",
    "x_element_type": "widget",
    "title": "Activity Loader Widget",
    "spanClass":"",
    "cssClass":"purple-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"3",
        "title":"Lesson 6",
        "badge":"icon-comments-alt",
        // "badge":"activity.png",
        "information_text":"Coming soon",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature.",
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "7",
    "x_element_type": "widget",
    "title": "Activity Loader Widget",
    "spanClass":"",
    "cssClass":"purple-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"3",
        "title":"Lesson 7",
        "badge":"icon-comment-alt",
        // "badge":"activity.png",
        "information_text":"Coming soon",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature.",
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "8",
    "x_element_type": "widget",
    "title": "Activity Loader Widget",
    "spanClass":"",
    "cssClass":"purple-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"3",
        "title":"Lesson 8",
        "badge":"icon-comment",
        // "badge":"activity.png",
        "information_text":"Coming soon",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature.",
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "9",
    "x_element_type": "widget",
    "title": "Activity Calendar Loader Widget",
    "spanClass":"",
    "cssClass":"yellow-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"19",
        "title":"Do",
        "badge":"icon-calendar",
        // "badge":"do.png",
        "information_text":"Learn How to Monitor &amp; Schedule Your Activities",
        "progression_information_text":"",
        "style_classes":"background_do"
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView; return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "10",
    "x_element_type": "widget",
    "title": "Thought Record Loader Widget",
    "spanClass":"",
    "cssClass":"yellow-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses a thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"14",
        "title":"Think &amp; Feel",
        // "badge":"<i class='icon-calendar'></i>",
        "badge":"thought.png",
        "information_text":"Learn to Understand your Thoughts &amp; Feelings",
        "progression_information_text":"",
        "style_classes":"background_think"
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView; return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "11",
    "x_element_type": "widget",
    "title": "Graph Loader Widget",
    "spanClass":"",
    "cssClass":"red-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"5",
        "title":"Mood",
        "badge":"icon-signal",
        // "badge":"graph.png",
        "information_text":"Up next!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {}  }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "12",
    "x_element_type": "widget",
    "title": "Social Loader Widget",
    "spanClass":"",
    "cssClass":"green-tile",
    "creator_guid": "",
    "content_description": "A widget that connects to the social explorer",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"2",
        "title":"Person 1",
        "badge":"icon-user",
        // "badge":"social.png",
        "information_text":"Add friends!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "13",
    "x_element_type": "widget",
    "title": "Social Loader Widget",
    "spanClass":"",
    "cssClass":"green-tile",
    "creator_guid": "",
    "content_description": "A widget that connects to the social explorer",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"2",
        "title":"Person 2",
        "badge":"icon-user",
        // "badge":"social.png",
        "information_text":"Add friends!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "14",
    "x_element_type": "widget",
    "title": "Social Loader Widget",
    "spanClass":"",
    "cssClass":"green-tile",
    "creator_guid": "",
    "content_description": "A widget that connects to the social explorer",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"2",
        "title":"Person 3",
        "badge":"icon-user",
        // "badge":"social.png",
        "information_text":"Add friends!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "15",
    "x_element_type": "widget",
    "title": "Social Loader Widget",
    "spanClass":"",
    "cssClass":"green-tile",
    "creator_guid": "",
    "content_description": "A widget that connects to the social explorer",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"2",
        "title":"Person 4",
        "badge":"icon-user",
        // "badge":"social.png",
        "information_text":"Add friends!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "16",
    "x_element_type": "widget",
    "title": "Social Loader Widget",
    "spanClass":"",
    "cssClass":"green-tile",
    "creator_guid": "",
    "content_description": "A widget that connects to the social explorer",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"2",
        "title":"Person 5",
        "badge":"icon-user",
        // "badge":"social.png",
        "information_text":"Add friends!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "17",
    "x_element_type": "widget",
    "title": "Social Loader Widget",
    "spanClass":"",
    "cssClass":"green-tile",
    "creator_guid": "",
    "content_description": "A widget that connects to the social explorer",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"2",
        "title":"Person 6",
        "badge":"icon-user",
        // "badge":"social.png",
        "information_text":"Add friends!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "18",
    "x_element_type": "widget",
    "title": "Social Loader Widget",
    "spanClass":"",
    "cssClass":"green-tile",
    "creator_guid": "",
    "content_description": "A widget that connects to the social explorer",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"2",
        "title":"Person 7",
        "badge":"icon-user",
        // "badge":"social.png",
        "information_text":"Add friends!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "19",
    "x_element_type": "widget",
    "title": "Social Loader Widget",
    "spanClass":"",
    "cssClass":"green-tile",
    "creator_guid": "",
    "content_description": "A widget that connects to the social explorer",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"2",
        "title":"Person 8",
        "badge":"icon-user",
        // "badge":"social.png",
        "information_text":"Add friends!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "20",
    "x_element_type": "widget",
    "title": "Timeline Loader Widget",
    "spanClass":"",
    "cssClass":"blue-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"6",
        "title":"Quiz",
        "badge":"icon-pencil",
        "information_text":"Take some quizzes to learn more about yourseslf",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "21",
    "x_element_type": "widget",
    "title": "Timeline Loader Widget",
    "spanClass":"",
    "cssClass":"blue-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"6",
        "title":"Quotes",
        "badge":"icon-quote-left",
        "information_text":"'Keep on keepin' on' -- Elmo.",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "22",
    "x_element_type": "widget",
    "title": "Timeline Loader Widget",
    "spanClass":"",
    "cssClass":"blue-tile",
    "creator_guid": "",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"6",
        "title":"Games",
        "badge":"timeline.png",
        "information_text":"A round of 2 Truths and a Lie",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "23",
    "x_element_type": "widget",
    "title": "Timeline Loader Widget",
    "creator_guid": "",
    "spanClass":"",
    "cssClass":"blue-tile",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"6",
        "title":"",
        "badge":"timeline.png",
        "information_text":"Keep logging!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
},{
    "guid": "24",
    "x_element_type": "widget",
    "title": "Timeline Loader Widget",
    "creator_guid": "",
    "spanClass":"",
    "cssClass":"blue-tile",
    "content_description": "A widget that accesses the activity and thought record collection to display content",
    "content": "",
    "input_data_type": null,
    "output_data_type": null,
    "active_membership": "",
    "x_methods": null,
    "metacontent_internal": null,
    "metacontent_external": { 
        "points_to_xelement":"6",
        "title":"Connect 5",
        "badge":"timeline.png",
        "information_text":"Keep logging!",
        "progression_information_text":"",
        "style_classes":"",
        "tooltip_content":"Use more of <em>ThinkFeelDo</em> to unlock this feature."
    },
    "version": null,
    "authorization_rule_guids_list": null,
    "view": "(function () { var this_view = WidgetView.extend({ events: {} }); return this_view; }) ();",
    "days_in_treatment": null,
    "is_presentational": "true",
    "is_standalone": "true",
    "requires_children": "false",
    "produces_instantiated_data": "false",
    "replace_remote_version": "false",
    "transmittable_to_client_at": "2011-11-16 00:00:00 +0000",
    "created_at": "2011-11-16 00:00:00 +0000",
    "updated_at": "2011-11-16 00:00:00 +0000",
    "children_guids": "[]",
    "parent_guids": "[]"
}]